# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-07 10:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happiness', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('hearts', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('score', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('difficulty', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=30)),
                ('due_date', models.DateTimeField()),
                ('done_progress', models.IntegerField()),
                ('score', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.FulfillUser')),
            ],
        ),
    ]
